### ISSUE TITLE
Getting startet

### ISSUE THREAD

**Issue by andreas-becker** [veracrypt/veracrypt.github.io#1]
@idrassi What about hosting and editing the website here?
I could do an initial website (f.e. based on this template: https://pages-themes.github.io/cayman/)
And then it might be easy to edit/update by merging pull requests.

**Comment by idrassi** [comment]
That was my idea at first when codeplex closed down but I decided finally to host the website on a dedicated server for various reasons. One aspect is to protect privacy of visitors of VeraCrypt website by not allowing their visit statistics and usage to be gathered by a third party. Another aspect is to have full control about how content is served and hosted (because of the nature of VeraCrypt, you never know what can happen if someone else control website hosting).

So, for now, I don't plan to use Github for website hosting.

**Comment by andreas-becker** [comment]
Ok, and how about creating a repo for the website? That way we all can work/optimise your website and you can decide what should be merged. You then could checkout the repo on your server or local instance and put it on a server wherever you want.
